#!/usr/bin/env bash
# Auto-generated by generate.sh
# OpenCode hook script - runs on various lifecycle events
# Place in .opencode/hooks/ and configure in oh-my-opencode.json

HOOK_EVENT="${1:-unknown}"

case "$HOOK_EVENT" in
    "chat.message")
        echo "📋 [OpenCode] Message received"
        ;;
    "session.create")
        echo "🚀 [OpenCode] Session started"
        cat .ai/MEMORY.md 2>/dev/null || echo "No memory file found"
        ;;
    "session.error")
        echo "❌ [OpenCode] Session error"
        ;;
    *)
        echo "ℹ️ [OpenCode] Event: $HOOK_EVENT"
        ;;
esac

